In [12]:
import pandas as pd

df_2023 = pd.read_csv("data/raw/halfmarathon_wroclaw_2023__final.csv")
df_2024 = pd.read_csv("data/raw/halfmarathon_wroclaw_2024__final.csv")

print("2023:", df_2023.shape)
print("2024:", df_2024.shape)

2023: (8950, 1)
2024: (13007, 1)

In [13]:
df_2023.head()

  Miejsce;Numer startowy;Imię;Nazwisko;Miasto;Kraj;Drużyna;Płeć;Płeć Miejsce;Kategoria wiekowa;Kategoria wiekowa Miejsce;Rocznik;5 km Czas;5 km Miejsce Open;5 km Tempo;10 km Czas;10 km Miejsce Open;10 km Tempo;15 km Czas;15 km Miejsce Open;15 km Tempo;20 km Czas;20 km Miejsce Open;20 km Tempo;Tempo Stabilność;Czas;Tempo
0  1.0;1787;TOMASZ;GRYCKO;;POL;UKS BLIZA WŁADYSŁA...
1  2.0;3;ARKADIUSZ;GARDZIELEWSKI;WROCŁAW;POL;ARKA...
2  3.0;3832;KRZYSZTOF;HADAS;POZNAŃ;POL;;M;3;M20;1...
3  4.0;416;DAMIAN;DYDUCH;KĘPNO;POL;AZS POLITECHNI...
4  5.0;8476;KAMIL;MAŃKOWSKI;MIRKÓW;POL;PARKRUN WR...

In [14]:
df_2023.columns

Index(['Miejsce;Numer startowy;Imię;Nazwisko;Miasto;Kraj;Drużyna;Płeć;Płeć Miejsce;Kategoria wiekowa;Kategoria wiekowa Miejsce;Rocznik;5 km Czas;5 km Miejsce Open;5 km Tempo;10 km Czas;10 km Miejsce Open;10 km Tempo;15 km Czas;15 km Miejsce Open;15 km Tempo;20 km Czas;20 km Miejsce Open;20 km Tempo;Tempo Stabilność;Czas;Tempo'], dtype='object')

In [15]:
df_2023.shape

(8950, 1)

In [16]:
import pandas as pd

df_2023 = pd.read_csv(
    "data/raw/halfmarathon_wroclaw_2023__final.csv",
    sep=";"
)

df_2024 = pd.read_csv(
    "data/raw/halfmarathon_wroclaw_2024__final.csv",
    sep=";"
)

print("2023:", df_2023.shape)
print("2024:", df_2024.shape)

2023: (8950, 27)
2024: (13007, 27)

In [17]:
df_2023.columns.tolist()

['Miejsce',
 'Numer startowy',
 'Imię',
 'Nazwisko',
 'Miasto',
 'Kraj',
 'Drużyna',
 'Płeć',
 'Płeć Miejsce',
 'Kategoria wiekowa',
 'Kategoria wiekowa Miejsce',
 'Rocznik',
 '5 km Czas',
 '5 km Miejsce Open',
 '5 km Tempo',
 '10 km Czas',
 '10 km Miejsce Open',
 '10 km Tempo',
 '15 km Czas',
 '15 km Miejsce Open',
 '15 km Tempo',
 '20 km Czas',
 '20 km Miejsce Open',
 '20 km Tempo',
 'Tempo Stabilność',
 'Czas',
 'Tempo']

In [18]:
df_2023.head()

,Miejsce,Numer startowy,Imię,Nazwisko,Miasto,Kraj,Drużyna,Płeć,Płeć Miejsce,Kategoria wiekowa,...,10 km Tempo,15 km Czas,15 km Miejsce Open,15 km Tempo,20 km Czas,20 km Miejsce Open,20 km Tempo,Tempo Stabilność,Czas,Tempo
0,1.0,1787,TOMASZ,GRYCKO,NaN,POL,UKS BLIZA WŁADYSŁAWOWO,M,1.0,M30,...,2.926667,00:44:47,1.0,3.106667,01:01:43,1.0,3.386667,0.031400,01:04:59,3.080509
1,2.0,3,ARKADIUSZ,GARDZIELEWSKI,WROCŁAW,POL,ARKADIUSZGARDZIELEWSKI.PL,M,2.0,M30,...,2.983333,00:45:26,2.0,3.143333,01:03:08,2.0,3.540000,0.038000,01:06:23,3.146875
2,3.0,3832,KRZYSZTOF,HADAS,POZNAŃ,POL,NaN,M,3.0,M20,...,3.123333,00:47:34,3.0,3.236667,01:05:09,3.0,3.516667,0.024067,01:08:24,3.242475
3,4.0,416,DAMIAN,DYDUCH,KĘPNO,POL,AZS POLITECHNIKA OPOLSKA,M,4.0,M30,...,3.196667,00:48:49,5.0,3.330000,01:06:54,4.0,3.616667,0.025467,01:10:16,3.330963
4,5.0,8476,KAMIL,MAŃKOWSKI,MIRKÓW,POL,PARKRUN WROCŁAW,M,5.0,M20,...,3.276667,00:49:31,7.0,3.386667,01:07:27,5.0,3.586667,0.023000,01:10:27,3.339654

In [19]:
df_2023.shape

(8950, 27)

In [20]:
df_2023.columns.tolist()

['Miejsce',
 'Numer startowy',
 'Imię',
 'Nazwisko',
 'Miasto',
 'Kraj',
 'Drużyna',
 'Płeć',
 'Płeć Miejsce',
 'Kategoria wiekowa',
 'Kategoria wiekowa Miejsce',
 'Rocznik',
 '5 km Czas',
 '5 km Miejsce Open',
 '5 km Tempo',
 '10 km Czas',
 '10 km Miejsce Open',
 '10 km Tempo',
 '15 km Czas',
 '15 km Miejsce Open',
 '15 km Tempo',
 '20 km Czas',
 '20 km Miejsce Open',
 '20 km Tempo',
 'Tempo Stabilność',
 'Czas',
 'Tempo']

In [21]:
df = pd.concat([df_2023, df_2024], ignore_index=True)

print(df.shape)

(21957, 27)

In [22]:
df[['Płeć', 'Rocznik', '5 km Czas', 'Czas']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21957 entries, 0 to 21956
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Płeć       21946 non-null  object
 1   Rocznik    21472 non-null  float64
 2   5 km Czas  18411 non-null  object
 3   Czas       19902 non-null  object
dtypes: float64(1), object(3)
memory usage: 686.3+ KB

In [23]:
df[['Płeć', 'Rocznik', '5 km Czas', 'Czas']].isna().sum()

Płeć           11
Rocznik       485
5 km Czas    3546
Czas         2055
dtype: int64

In [24]:
df.shape

(21957, 27)

In [25]:
df_model = df[
    ['Płeć', 'Rocznik', '5 km Czas', 'Czas']
].copy()

df_model = df_model.dropna()

print(df_model.shape)

(17927, 4)

In [26]:
df_model.isna().sum()

Płeć         0
Rocznik      0
5 km Czas    0
Czas         0
dtype: int64

In [27]:
df_model[['5 km Czas', 'Czas']].head(10)

  5 km Czas      Czas
0  00:14:37  01:04:59
1  00:14:48  01:06:23
2  00:15:46  01:08:24
3  00:16:11  01:10:16
4  00:16:12  01:10:27
5  00:16:09  01:10:34
6  00:15:37  01:11:18
7  00:16:30  01:11:42
8  00:17:10  01:14:16
9  00:16:53  01:14:22

In [28]:
df_model["5km_seconds"] = (
    pd.to_timedelta(df_model["5 km Czas"])
    .dt.total_seconds()
)

df_model["halfmarathon_seconds"] = (
    pd.to_timedelta(df_model["Czas"])
    .dt.total_seconds()
)

df_model[
    ["5 km Czas", "5km_seconds",
     "Czas", "halfmarathon_seconds"]
].head()

  5 km Czas  5km_seconds      Czas  halfmarathon_seconds
0  00:14:37        877.0  01:04:59                3899.0
1  00:14:48        888.0  01:06:23                3983.0
2  00:15:46        946.0  01:08:24                4104.0
3  00:16:11        971.0  01:10:16                4216.0
4  00:16:12        972.0  01:10:27                4227.0

In [29]:
CURRENT_YEAR = 2024

df_model["wiek"] = CURRENT_YEAR - df_model["Rocznik"]

In [30]:
df_model[["Rocznik", "wiek"]].head()

   Rocznik  wiek
0   1992.0  32.0
1   1986.0  38.0
2   1996.0  28.0
3   1988.0  36.0
4   1995.0  29.0

In [31]:
df_model[
    ["Płeć", "wiek", "5km_seconds", "halfmarathon_seconds"]
].head()

  Płeć  wiek  5km_seconds  halfmarathon_seconds
0    M  32.0        877.0                3899.0
1    M  38.0        888.0                3983.0
2    M  28.0        946.0                4104.0
3    M  36.0        971.0                4216.0
4    M  29.0        972.0                4227.0

In [32]:
df_model[
    ["wiek", "5km_seconds", "halfmarathon_seconds"]
].describe()

               wiek   5km_seconds  halfmarathon_seconds
count  17927.000000  17927.000000          17927.000000
mean      41.615887   1672.398896           7392.332627
std       63.679861    246.903126           1212.071213
min       18.000000      0.000000           3843.000000
25%       32.000000   1501.000000           6544.000000
50%       39.000000   1660.000000           7240.000000
75%       46.000000   1833.000000           8128.000000
max     2024.000000   3825.000000          12512.000000

In [33]:
df_model["Płeć"].value_counts()

Płeć
M    12760
K     5167
Name: count, dtype: int64

In [34]:
X = df_model[
    ["Płeć", "wiek", "5km_seconds"]
]

y = df_model["halfmarathon_seconds"]

In [35]:
df_model[
    ["wiek", "5km_seconds", "halfmarathon_seconds"]
].describe()

               wiek   5km_seconds  halfmarathon_seconds
count  17927.000000  17927.000000          17927.000000
mean      41.615887   1672.398896           7392.332627
std       63.679861    246.903126           1212.071213
min       18.000000      0.000000           3843.000000
25%       32.000000   1501.000000           6544.000000
50%       39.000000   1660.000000           7240.000000
75%       46.000000   1833.000000           8128.000000
max     2024.000000   3825.000000          12512.000000

In [36]:
df_model["Płeć"].value_counts()

Płeć
M    12760
K     5167
Name: count, dtype: int64

In [37]:
df_model = df_model[
    (df_model["wiek"] >= 18) &
    (df_model["wiek"] <= 90) &
    (df_model["5km_seconds"] > 0)
].copy()

print(df_model.shape)

(17908, 7)

In [38]:
df_model[
    ["wiek", "5km_seconds", "halfmarathon_seconds"]
].describe()

               wiek   5km_seconds  halfmarathon_seconds
count  17908.000000  17908.000000          17908.000000
mean      39.623911   1672.380333           7391.771945
std       10.256530    246.453360           1211.286563
min       18.000000    877.000000           3843.000000
25%       32.000000   1500.750000           6544.000000
50%       39.000000   1660.000000           7240.000000
75%       46.000000   1833.000000           8127.250000
max       90.000000   3825.000000          12512.000000

In [39]:
df_model["gender"] = df_model["Płeć"].map({
    "M": 1,
    "K": 0
})

In [40]:
df_model[["Płeć", "gender"]].head()

  Płeć  gender
0    M       1
1    M       1
2    M       1
3    M       1
4    M       1

In [41]:
model_data = df_model[
    [
        "gender",
        "wiek",
        "5km_seconds",
        "halfmarathon_seconds"
    ]
].copy()

In [42]:
model_data.head()

   gender  wiek  5km_seconds  halfmarathon_seconds
0       1  32.0        877.0                3899.0
1       1  38.0        888.0                3983.0
2       1  28.0        946.0                4104.0
3       1  36.0        971.0                4216.0
4       1  29.0        972.0                4227.0

In [43]:
from pycaret.regression import *

In [44]:
reg_setup = setup(
    data=model_data,
    target="halfmarathon_seconds",
    session_id=42,
    verbose=False
)

In [45]:
best_model = compare_models()

In [46]:
final_model = finalize_model(best_model)

In [47]:
save_model(
    final_model,
    "models/halfmarathon_model"
)

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['gender', 'wiek', '5km_seconds'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('actual_estimator',
                  GradientBoostingRegressor(random_state=42))]),
 'models/halfmarathon_model.pkl')

In [48]:
import pandas as pd

test_runner = pd.DataFrame({
    "gender": [1],
    "wiek": [35],
    "5km_seconds": [1500]
})

predict_model(
    final_model,
    data=test_runner
)

   gender  wiek  5km_seconds  prediction_label
0       1    35         1500        6550.04434

In [49]:
from dotenv import load_dotenv
import os

load_dotenv(override=True)

print("ACCESS:", bool(os.getenv("DO_ACCESS_KEY")))
print("SECRET:", bool(os.getenv("DO_SECRET_KEY")))

ACCESS: True
SECRET: True

In [50]:
import boto3
from dotenv import load_dotenv
import os

load_dotenv(override=True)

client = boto3.client(
    "s3",
    endpoint_url=os.getenv("DO_ENDPOINT"),
    aws_access_key_id=os.getenv("DO_ACCESS_KEY"),
    aws_secret_access_key=os.getenv("DO_SECRET_KEY"),
)

response = client.list_objects_v2(
    Bucket=os.getenv("DO_BUCKET_NAME")
)

print(response)

#for bucket in response["Buckets"]:
#    print(bucket["Name"])

{'ResponseMetadata': {'RequestId': 'tx000009d0f2ba4a9ba7957-006a22bc9d-28ecb259-fra1c', 'HostId': '', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'tx000009d0f2ba4a9ba7957-006a22bc9d-28ecb259-fra1c', 'content-type': 'application/xml', 'date': 'Fri, 05 Jun 2026 12:10:05 GMT', 'strict-transport-security': 'max-age=15552000; includeSubDomains; preload', 'transfer-encoding': 'chunked'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Contents': [{'Key': 'data/raw/halfmarathon_wroclaw_2023__final.csv', 'LastModified': datetime.datetime(2026, 6, 5, 12, 0, 31, 811000, tzinfo=tzutc()), 'ETag': '"9da92a97c9484f41f24df7713a940a6a"', 'Size': 2008515, 'StorageClass': 'STANDARD'}, {'Key': 'data/raw/halfmarathon_wroclaw_2024__final.csv', 'LastModified': datetime.datetime(2026, 6, 5, 12, 2, 10, 145000, tzinfo=tzutc()), 'ETag': '"ac9a1d9629277a52fedcb57b53763207"', 'Size': 2651025, 'StorageClass': 'STANDARD'}, {'Key': 'models/halfmarathon_model.pkl', 'LastModified': datetime.datetime(2026, 6, 5, 12, 3, 18, 277000, tzinfo=tzutc()), 'ETag': '"1d9da2434e21c04663183b39f6d4b612"', 'Size': 190295, 'StorageClass': 'STANDARD'}], 'Name': 'halfmarathon-ai', 'Prefix': '', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 3}

In [51]:
client.upload_file(
    "data/raw/halfmarathon_wroclaw_2023__final.csv",
    os.getenv("DO_BUCKET_NAME"),
    "data/raw/halfmarathon_wroclaw_2023__final.csv"
)

print("Upload OK")

Upload OK

In [52]:
client.upload_file(
    "data/raw/halfmarathon_wroclaw_2024__final.csv",
    os.getenv("DO_BUCKET_NAME"),
    "data/raw/halfmarathon_wroclaw_2024__final.csv"
)

print("Upload 2024 OK")

Upload 2024 OK

In [53]:
client.upload_file(
    "models/halfmarathon_model.pkl",
    os.getenv("DO_BUCKET_NAME"),
    "models/halfmarathon_model.pkl"
)

print("Model Upload OK")

Model Upload OK

In [54]:
import os

client.download_file(
    os.getenv("DO_BUCKET_NAME"),
    "data/raw/halfmarathon_wroclaw_2023__final.csv",
    "temp_2023.csv"
)

print("Download OK")

Download OK

In [55]:
import pandas as pd

df_test = pd.read_csv(
    "temp_2023.csv",
    sep=";"
)

print(df_test.shape)

(8950, 27)

In [1]:
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv(override=True)

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)

response = client.responses.create(
    model="gpt-4.1-mini",
    input="Napisz tylko słowo OK"
)

print(response.output_text)

OK

In [2]:
from openai import OpenAI
from dotenv import load_dotenv
import os
import json

load_dotenv(override=True)

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)

user_text = """
Jestem kobietą, mam 38 lat,
5 km biegam w 18 minut
"""

response = client.responses.create(
    model="gpt-4.1-mini",
    input=f"""
Wyciągnij dane z tekstu.

Zwróć WYŁĄCZNIE JSON.

Format:

{{
  "gender": 0,
  "wiek": 0,
  "5km_seconds": 0
}}

Zasady:
- kobieta = 0
- mężczyzna = 1
- czas podaj w sekundach

Tekst:
{user_text}
"""
)

print(response.output_text)

```json
{
  "gender": 0,
  "wiek": 38,
  "5km_seconds": 1080
}
```

In [8]:
import json
import pandas as pd
from pycaret.regression import predict_model

clean_json = (
    response.output_text
    .replace("```json", "")
    .replace("```", "")
    .strip()
)

data = json.loads(clean_json)

test_runner = pd.DataFrame({
    "gender": [data["gender"]],
    "wiek": [data["wiek"]],
    "5km_seconds": [data["5km_seconds"]]
})

prediction = predict_model(
    final_model,
    data=test_runner
)

prediction[["prediction_label"]]

   prediction_label
0       4762.898318

In [7]:
from pycaret.regression import load_model

final_model = load_model("models/halfmarathon_model")

print(type(final_model))

Transformation Pipeline and Model Successfully Loaded
<class 'pycaret.internal.pipeline.Pipeline'>